### PR TITLE
Add CLDR 32.0.1

### PR DESCRIPTION
**Pull request by c960657**
This adds the CLDR 32.0.1 data set, released on 12 December, 2017.

[Release notes](http://cldr.unicode.org/index/downloads/cldr-32)

### CODE REVIEW

**Comment by mlocati** [comment]
How did you compiled these data? I [have an error](https://unicode.org/cldr/trac/ticket/10860)...

**Comment by c960657** [comment]
Oh, I forgot to include this in my patch. I removed `-o true`. It isn't clear to me what the purpose of this switch is, but I generated the CLDR 31 dataset without it, and it was identical to the one in Git (except for some sorting in a single locale which I assume is due to changes in PHPs collator).

**Comment by mlocati** [comment]
The `docs/state.json` file should have been updated by `punic-build-data` to include this CLDR version...
Did you forget to commit it? Otherwise we have problems in the build script...

**Comment by c960657** [comment]
Sorry, my bad again. The build script works like a charm :-)

**Comment by mlocati** [comment]
Thank you!

**Pull request merged**
